name: Check URLs

on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时运行一次
  workflow_dispatch:

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check URLs
      id: check
      run: |
        urls=("http://xn--mpus5ehyb.us.kg/api.php/timming/index.html?enforce=1&name=hw8" "https://xn--mpus5ehyb.us.kg/api.php/timming/index.html?enforce=1&name=%E8%87%AA%E5%8A%A8%E9%87%87%E9%9B%86" "https://xn--mpus5ehyb.us.kg/api.php/timming/index.html?enforce=1&name=liangzi")
        results=""
        for url in "${urls[@]}"; do
          response=$(curl -o /dev/null -s -w "%{http_code}\n" "$url")
          if [ "$response" -eq 200 ]; then
            results+="URL: $url is up\n"
          else
            results+="URL: $url is down\n"
          fi
          sleep 10
        done
        echo "$results" > result.txt

    - name: Send Telegram Message
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        MESSAGE=$(cat result.txt)
        curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ env.TELEGRAM_CHAT_ID }} -d text="$MESSAGE"
