name: Refresh URLs and Notify Telegram

on:
  schedule:
    - cron: '0 0 */3 * *'  # 每3天运行一次
  workflow_dispatch:

jobs:
  refresh-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Refresh URLs
      run: |
        urls=("https://uskg.nyc.mn/" "https://wencai.nyc.mn/" "https://tencent.nyc.mn/" "https://ppua.nyc.mn")  # 替换为你的 URL 列表
        for url in "${urls[@]}"; do
          curl -s "$url" > /dev/null
          sleep 10
        done

    - name: Send Telegram Notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        STATUS="URLs refreshed successfully"
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="$STATUS"
